name: Release to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-pubish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Install Python
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
      - name: Install build dependencies
        run: python -m pip install -U setuptools build wheel
      - name: Build distributions
        run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@9b8e7336db3f96a2939a3e9fa827c62f466ca60d # master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
