name: Python Unit CI
on: [push, pull_request]
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout
      uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: python -m pip install tox
    - name: Test
      run: python -m tox -e py-${{ matrix.platform }}
